import { serviceCities } from '../config/env.js'

const serviceArea = `${serviceCities.length} service cities`

export const defaultActivities = [
  {
    id: 'pottery-party',
    category: 'workshop',
    title: 'Pottery Party',
    short: 'Shape, spin and paint your own ceramic keepsake with a patient studio artist.',
    description:
      'A warm, hands-on pottery experience designed for complete beginners. Your facilitator brings clay, tools, aprons and plenty of encouragement while every guest creates something personal to take home.',
    price: 4699,
    priceUnit: 'per group',
    duration: '2 hrs',
    guests: '2–10 guests',
    location: serviceArea,
    rating: 4.9,
    reviews: 320,
    badge: 'Most loved',
    minLeadDays: 1,
    image:
      'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=85',
    includes: ['Clay and pottery tools', 'Aprons and workspace setup', 'Guided 2-hour session', 'One creation per guest'],
  },
  {
    id: 'magic-and-games',
    category: 'birthday',
    title: 'Magic & Games',
    short: 'An interactive magic show and energetic games designed around the birthday child.',
    description:
      'A lively celebration package combining a professional magic show with age-appropriate group games. The host keeps the children involved from the first trick to the final applause.',
    price: 3999,
    priceUnit: 'per event',
    duration: '90 mins',
    guests: '15–30 guests',
    location: serviceArea,
    rating: 4.8,
    reviews: 210,
    badge: 'Popular',
    minLeadDays: 2,
    image:
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=85',
    includes: ['Interactive magic show', 'Party games', 'Music and basic props', 'Bilingual host'],
  },
  {
    id: 'wedding-live-art',
    category: 'wedding',
    title: 'Wedding Live Art',
    short: 'A live artist captures your celebration and creates a one-of-a-kind heirloom.',
    description:
      'Watch an artist turn one meaningful moment into a finished artwork during your event. The composition and palette are discussed in advance so the final piece feels completely yours.',
    price: 7499,
    priceUnit: 'starting price',
    duration: '4 hrs',
    guests: 'Any event size',
    location: serviceArea,
    rating: 5.0,
    reviews: 118,
    badge: 'Signature',
    minLeadDays: 5,
    image:
      'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=85',
    includes: ['Pre-event consultation', 'Live event painting', 'Professional art materials', 'Finished artwork'],
  },
  {
    id: 'perfume-making-stall',
    category: 'wedding',
    title: 'Perfume Making Stall',
    short: 'Guests create a customised perfume by choosing their favourite fragrances.',
    description:
      'A fun and luxurious wedding experience where guests explore fragrance notes, blend a personalised perfume and take their creation home as a memorable favour.',
    price: null,
    priceUnit: 'custom package',
    duration: '3 hrs',
    guests: 'Up to 80 guests',
    location: serviceArea,
    rating: null,
    reviews: 0,
    badge: 'Wedding favourite',
    minLeadDays: 7,
    image:
      'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=85',
    includes: ['Fragrance selection', 'Mixing station and bottles', 'Event facilitator', 'Personalised take-home perfume'],
  },
  {
    id: 'face-art-stall',
    category: 'wedding',
    title: 'Face Art Stall',
    short: 'Quick and beautiful face designs using vibrant paints, shimmer and glitter.',
    description:
      'Add colour and sparkle to every celebration with elegant face art for guests of all ages. Designs can be coordinated with the wedding theme and guest preferences.',
    price: null,
    priceUnit: 'custom package',
    duration: '3 hrs',
    guests: 'Up to 60 guests',
    location: serviceArea,
    rating: null,
    reviews: 0,
    badge: 'Colourful',
    minLeadDays: 5,
    image:
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=85',
    includes: ['Professional face artist', 'Skin-friendly paints', 'Glitter and shimmer options', 'Complete stall setup'],
  },
  {
    id: 'lipstick-making-stall',
    category: 'wedding',
    title: 'Lipstick Making Stall',
    short: 'Guests design their own lipstick shades using safe, skin-friendly ingredients.',
    description:
      'A creative and trendy wedding activity where guests mix pigments, choose their shade and take home a lipstick made especially for them.',
    price: null,
    priceUnit: 'custom package',
    duration: '3 hrs',
    guests: 'Up to 50 guests',
    location: serviceArea,
    rating: null,
    reviews: 0,
    badge: 'Trending',
    minLeadDays: 7,
    image:
      'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=1200&q=85',
    includes: ['Skin-friendly ingredients', 'Shade mixing station', 'Lipstick containers', 'Guided making experience'],
  },
  {
    id: 'glitter-art-stall',
    category: 'wedding',
    title: 'Glitter Art Stall',
    short: 'Sparkling glitter tattoos and decorative art for hands and face.',
    description:
      'A lively, photo-friendly stall offering beautiful temporary glitter designs. It is a fun addition for children and adults at wedding celebrations.',
    price: null,
    priceUnit: 'custom package',
    duration: '3 hrs',
    guests: 'Up to 70 guests',
    location: serviceArea,
    rating: null,
    reviews: 0,
    badge: 'Guest favourite',
    minLeadDays: 5,
    image:
      'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=1200&q=85',
    includes: ['Professional glitter artist', 'Skin-safe glitter', 'Design catalogue', 'Complete stall setup'],
  },
  {
    id: 'lip-balm-making-stall',
    category: 'wedding',
    title: 'Lip Balm Making Stall',
    short: 'A soothing DIY station where guests make natural lip balms.',
    description:
      'Simple, fun and useful, this guided stall lets guests blend their own natural lip balm and package it as a perfect take-home gift.',
    price: null,
    priceUnit: 'custom package',
    duration: '3 hrs',
    guests: 'Up to 60 guests',
    location: serviceArea,
    rating: null,
    reviews: 0,
    badge: 'Take-home gift',
    minLeadDays: 7,
    image:
      'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=1200&q=85',
    includes: ['Natural ingredients', 'Mixing tools', 'Lip balm containers', 'Guided DIY station'],
  },
  {
    id: 'resin-keychain-stall',
    category: 'wedding',
    title: 'Resin Keychain Stall',
    short: 'Guests design resin keychains using colours, charms, glitter and more.',
    description:
      'A personalised keepsake experience where guests create their own resin keychain—a small memory they can carry long after the wedding.',
    price: null,
    priceUnit: 'custom package',
    duration: '3 hrs',
    guests: 'Up to 60 guests',
    location: serviceArea,
    rating: null,
    reviews: 0,
    badge: 'Personalised',
    minLeadDays: 7,
    image:
      'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?auto=format&fit=crop&w=1200&q=85',
    includes: ['Resin and moulds', 'Colours, glitter and charms', 'Keychain fittings', 'Event facilitator'],
  },
  {
    id: 'block-making-stall',
    category: 'wedding',
    title: 'Block Making Stall',
    short: 'A hands-on printing station where guests create patterns with decorative blocks.',
    description:
      'Guests choose motifs, colours and layouts before printing a personalised design. The activity is relaxed, creative and makes a distinctive wedding keepsake.',
    price: null,
    priceUnit: 'custom package',
    duration: '3 hrs',
    guests: 'Up to 60 guests',
    location: serviceArea,
    rating: null,
    reviews: 0,
    badge: 'Hands-on',
    minLeadDays: 7,
    image:
      'https://images.unsplash.com/photo-1581783898377-1c85bf937427?auto=format&fit=crop&w=1200&q=85',
    includes: ['Printing blocks', 'Fabric-safe colours', 'Practice material', 'Guided stall experience'],
  },
  {
    id: 'little-makers-studio',
    category: 'birthday',
    title: 'Little Makers Studio',
    short: 'A colourful guided craft station where every child makes a party keepsake.',
    description:
      'A beautifully styled craft table with a friendly facilitator and age-appropriate materials. Children can explore freely while still completing a polished take-home project.',
    price: 5499,
    priceUnit: 'per event',
    duration: '2 hrs',
    guests: '10–25 guests',
    location: serviceArea,
    rating: 4.9,
    reviews: 144,
    badge: 'New',
    minLeadDays: 2,
    image:
      'https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=1200&q=85',
    includes: ['Craft supplies', 'Styled activity table', 'Facilitator', 'Take-home creations'],
  },
  {
    id: 'wedding-couple-quiz',
    category: 'wedding',
    title: 'The Couple Quiz',
    short: 'A polished emcee-led game that gets both families laughing and talking.',
    description:
      'A personalised, warm and never-awkward game experience built around the couple. We prepare the prompts with you and handle the complete on-stage flow.',
    price: 8999,
    priceUnit: 'per event',
    duration: '60 mins',
    guests: '50–250 guests',
    location: serviceArea,
    rating: 4.8,
    reviews: 89,
    badge: 'Crowd favourite',
    minLeadDays: 5,
    image:
      'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=85',
    includes: ['Professional emcee', 'Personalised game plan', 'Props', 'Event coordination'],
  },
  {
    id: 'resin-keepsake-workshop',
    category: 'workshop',
    title: 'Resin Keepsake Workshop',
    short: 'Create luminous coasters or trays using colour, texture and pressed botanicals.',
    description:
      'A calm, guided resin session with pre-measured materials and a choice of palettes. Perfect for friends, date nights and small team experiences.',
    price: 3499,
    priceUnit: 'per group',
    duration: '2 hrs',
    guests: '2–8 guests',
    location: serviceArea,
    rating: 4.8,
    reviews: 172,
    badge: 'Trending',
    minLeadDays: 1,
    image:
      'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?auto=format&fit=crop&w=1200&q=85',
    includes: ['Resin and pigments', 'Moulds and tools', 'Safety equipment', 'Two finished pieces per guest'],
  },
  {
    id: 'carnival-games',
    category: 'birthday',
    title: 'Mini Carnival Games',
    short: 'A cheerful set of skill games with a coordinator, prizes and colourful counters.',
    description:
      'Turn your venue into a compact carnival with games that work for mixed age groups. Our coordinator sets up, runs each round and keeps the pace moving.',
    price: 6499,
    priceUnit: 'per event',
    duration: '2 hrs',
    guests: '20–50 guests',
    location: serviceArea,
    rating: 4.7,
    reviews: 98,
    badge: 'High energy',
    minLeadDays: 3,
    image:
      'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=85',
    includes: ['Four game counters', 'Game coordinator', 'Setup and pack-down', 'Basic prizes'],
  },
  {
    id: 'guest-portrait-bar',
    category: 'wedding',
    title: 'Guest Portrait Bar',
    short: 'Quick, elegant illustrated portraits that double as unforgettable wedding favours.',
    description:
      'Guests sit for a few minutes while our illustrator creates a charming personalised portrait. Every piece is presented in a protective sleeve to take home.',
    price: 12999,
    priceUnit: 'starting price',
    duration: '4 hrs',
    guests: 'Up to 80 portraits',
    location: serviceArea,
    rating: 4.9,
    reviews: 76,
    badge: 'Premium',
    minLeadDays: 7,
    image:
      'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=85',
    includes: ['Live illustrator', 'Premium paper', 'Personalised name cards', 'Portrait sleeves'],
  },
  {
    id: 'texture-art-lab',
    category: 'workshop',
    title: 'Texture Art Lab',
    short: 'Build a tactile modern canvas with palette knives, sculpting paste and colour.',
    description:
      'Learn the satisfying process of layering texture and shaping a contemporary artwork. Choose from several beginner-friendly compositions and take home a display-ready canvas.',
    price: 2999,
    priceUnit: 'per group',
    duration: '2 hrs',
    guests: '2–10 guests',
    location: serviceArea,
    rating: 4.8,
    reviews: 132,
    badge: 'Beginner friendly',
    minLeadDays: 1,
    image:
      'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=1200&q=85',
    includes: ['Canvas and art materials', 'Palette knives', 'Instructor', 'Protective apron'],
  },
]

const catalogueImages = {
  craft: 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?auto=format&fit=crop&w=1200&q=85',
  celebration: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=85',
  children: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=1200&q=85',
  colour: 'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=1200&q=85',
  fragrance: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=85',
  makeup: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=1200&q=85',
  performance: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=85',
  wedding: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=85',
}

const weddingCatalogue = [
  ['wedding-block-printing', 'Block Printing', 'A guided block-printing counter where guests create a patterned keepsake.', 'craft'],
  ['wedding-perfume-making', 'Perfume Making / Fragrance Blending', 'Guests blend fragrance notes and create a personalised scent to take home.', 'fragrance'],
  ['wedding-lipstick-making', 'Lipstick Making', 'A colour-mixing experience where guests create a lipstick shade of their own.', 'makeup'],
  ['wedding-candle-making', 'Candle Making', 'Guests pour and personalise a scented candle as a memorable wedding favour.', 'fragrance'],
  ['wedding-charm-bar', 'Charm Bar', 'A styled charm station for assembling personalised bracelets and accessories.', 'craft'],
  ['wedding-potpourri-making', 'Potpourri Making', 'Guests compose a fragrant potpourri blend with botanicals and decorative details.', 'fragrance'],
  ['wedding-magnetic-memory-making', 'Magnetic Memory Making', 'Turn favourite moments into personalised magnets guests can take home.', 'craft'],
  ['wedding-art-corner', 'Art Corner', 'An inviting open-art station with guided creative activities for every age.', 'colour'],
  ['wedding-kundan-mehendi', 'Kundan Mehendi', 'A festive Kundan-inspired mehendi experience designed for wedding celebrations.', 'wedding'],
  ['wedding-pottery', 'Pottery', 'A hands-on pottery counter where guests shape and decorate a clay keepsake.', 'craft'],
  ['wedding-nail-care-parlour', 'Nail Care Parlour', 'A polished mini nail-care lounge offering quick event-ready treatments.', 'makeup'],
  ['wedding-resin-art-stall', 'Resin Art Stall', 'Guests create a colourful resin keepsake with guidance from an experienced artist.', 'craft'],
  ['wedding-diy-games', 'DIY Games', 'Creative do-it-yourself games that keep guests engaged throughout the celebration.', 'celebration'],
  ['wedding-face-glitter-art', 'Face Art & Glitter Art', 'Skin-friendly face art and glitter designs that add sparkle to wedding photos.', 'makeup'],
  ['wedding-frame-your-photos', 'Frame Your Photos', 'Guests decorate a photo frame and leave with a personalised event memory.', 'craft'],
  ['wedding-jute-bangles', 'Jute Bangles Making', 'A guided station for wrapping and decorating handcrafted jute bangles.', 'craft'],
  ['wedding-games', 'Wedding Games', 'Warm, inclusive hosted games created to bring both families together.', 'celebration'],
  ['wedding-instant-polaroid', 'Instant Polaroid', 'An instant-photo counter that gives guests a printed memory within minutes.', 'wedding'],
  ['wedding-kathputli-show', 'Kathputli Show', 'A colourful traditional Kathputli performance for guests of every generation.', 'performance'],
  ['wedding-puppet-show', 'Puppet Show', 'A lively puppet performance with stories, humour and audience interaction.', 'performance'],
  ['wedding-magic-show', 'Magic Show', 'An interactive live magic performance designed for a mixed-age wedding audience.', 'performance'],
  ['wedding-live-mehendi-block-printing', 'Live Mehendi / Block Printing Stall', 'A two-in-one live stall combining mehendi artistry with block printing.', 'wedding'],
  ['wedding-jewellery-box-making', 'DIY Jewellery Box Making', 'Guests decorate a compact jewellery box and take home their finished creation.', 'craft'],
  ['wedding-live-vintage-frame', 'Live Vintage Frame', 'A styled vintage-frame experience for distinctive portraits and guest memories.', 'wedding'],
  ['wedding-coffee-mug-engraving', 'Coffee Mug Engraving', 'Personalised mug engraving completed live as a useful wedding keepsake.', 'craft'],
  ['wedding-tarot-card-reading', 'Tarot Card Reading', 'A tasteful tarot-reading corner offering short, engaging personal sessions.', 'wedding'],
  ['wedding-wax-fragrance', 'Wax Fragrance', 'Guests create a decorative scented-wax piece using a curated fragrance palette.', 'fragrance'],
].map(([id, title, short, imageKey]) => ({
  id,
  category: 'wedding',
  title,
  short,
  description: `${short} The Brush & Colours team brings the materials, complete counter setup and facilitation so the experience runs smoothly at your venue.`,
  price: 12000,
  priceUnit: 'for 50 people',
  duration: '3 hrs',
  guests: '50 people',
  location: serviceArea,
  rating: null,
  reviews: 0,
  badge: 'Wedding experience',
  minLeadDays: 5,
  image: catalogueImages[imageKey],
  includes: ['Complete activity setup', 'Materials for 50 people', 'Professional facilitator', 'Setup and pack-down'],
  guestPricing: { enabled: false, includedGuests: 50, percentPerExtraGuest: 0, maxGuests: 50 },
}))

const birthdayCatalogue = [
  ['birthday-bracelet-making', 'Bracelet Making', 'Children design and assemble colourful bracelets they can proudly take home.', 'craft'],
  ['birthday-face-painting', 'Face Painting', 'Skin-friendly face painting with a playful choice of child-approved designs.', 'makeup'],
  ['birthday-sunglasses-decorating', 'DIY Sunglasses Decorating', 'Children customise fun sunglasses using charms, colours and decorations.', 'colour'],
  ['birthday-tote-bag-painting', 'Tote Bag Painting', 'A guided fabric-painting activity with one reusable tote bag for every child.', 'colour'],
  ['birthday-bedazzle-art', 'Bedazzle Art', 'A sparkling craft session using gems and decorative details on a keepsake.', 'craft'],
  ['birthday-bag-charm-making', 'Bag Charm Making', 'Children combine beads and charms to make a personalised bag accessory.', 'craft'],
  ['birthday-mdf-painting', 'MDF Painting', 'A cheerful painting session with ready-to-decorate MDF shapes.', 'colour'],
  ['birthday-mosaic-art', 'Mosaic Art', 'Children arrange bright mosaic pieces into a display-ready creative project.', 'colour'],
  ['birthday-beaded-bracelet-making', 'DIY Beaded Bracelet Making', 'A bead bar with guided bracelet making for a relaxed, social party activity.', 'craft'],
  ['birthday-slime-making', 'DIY Slime Making', 'A supervised slime lab where children mix colours, textures and safe add-ins.', 'children'],
  ['birthday-fluid-art', 'Fluid Art', 'Children pour and swirl colours to create a one-of-a-kind abstract artwork.', 'colour'],
  ['birthday-fun-games', 'Fun Games', 'Age-appropriate party games managed by an energetic event facilitator.', 'celebration'],
  ['birthday-anchoring', 'Anchoring', 'A friendly host keeps the birthday programme, games and announcements flowing.', 'performance'],
].map(([id, title, short, imageKey]) => ({
  id,
  category: 'birthday',
  title,
  short,
  description: `${short} The package includes materials, preparation and an experienced facilitator for an organised, child-friendly celebration at your venue.`,
  price: 10000,
  priceUnit: 'for 15 kids',
  duration: '2 hrs',
  guests: '15 kids',
  location: serviceArea,
  rating: null,
  reviews: 0,
  badge: 'Birthday favourite',
  minLeadDays: 3,
  image: catalogueImages[imageKey],
  includes: ['Complete activity setup', 'Materials for 15 kids', 'Professional facilitator', 'Setup and pack-down'],
  guestPricing: { enabled: false, includedGuests: 15, percentPerExtraGuest: 0, maxGuests: 15 },
}))

defaultActivities.push(...weddingCatalogue, ...birthdayCatalogue)
