export const seedActivities = [
  ['pottery-party', 'Pottery Party', 'workshop', 4699, 'per group', 1],
  ['magic-and-games', 'Magic & Games', 'birthday', 3999, 'per event', 2],
  ['wedding-live-art', 'Wedding Live Art', 'wedding', 7499, 'starting price', 5],
  ['perfume-making-stall', 'Perfume Making Stall', 'wedding', null, 'custom package', 7],
  ['face-art-stall', 'Face Art Stall', 'wedding', null, 'custom package', 5],
  ['lipstick-making-stall', 'Lipstick Making Stall', 'wedding', null, 'custom package', 7],
  ['glitter-art-stall', 'Glitter Art Stall', 'wedding', null, 'custom package', 5],
  ['lip-balm-making-stall', 'Lip Balm Making Stall', 'wedding', null, 'custom package', 7],
  ['resin-keychain-stall', 'Resin Keychain Stall', 'wedding', null, 'custom package', 7],
  ['block-making-stall', 'Block Making Stall', 'wedding', null, 'custom package', 7],
  ['little-makers-studio', 'Little Makers Studio', 'birthday', 5499, 'per event', 2],
  ['wedding-couple-quiz', 'The Couple Quiz', 'wedding', 8999, 'per event', 5],
  ['resin-keepsake-workshop', 'Resin Keepsake Workshop', 'workshop', 3499, 'per group', 1],
  ['carnival-games', 'Mini Carnival Games', 'birthday', 6499, 'per event', 3],
  ['guest-portrait-bar', 'Guest Portrait Bar', 'wedding', 12999, 'starting price', 7],
  ['texture-art-lab', 'Texture Art Lab', 'workshop', 2999, 'per group', 1],
]
